### ISSUE TITLE
Splash Screen

### ISSUE THREAD

**Issue by kfpotts1** [kfpotts1/mp.Me#14]

**Comment by kfpotts1** [comment]
This appears when the user first opens the software.

done:
The splash screen appears on launch, and can recognize whether the software is being opened for the first time.

**Comment by storytellerr** [comment]
i want to contribute to this project can i start work?

**Comment by wisejackfr0st** [comment]
4 hours, most of it was testing issues and fighting with IntelliJ/JUnit

**Comment by storytellerr** [comment]
i want to work on this project please guide me what the owner wants to build. till now i am in a confused situation. please elaborate so i can start working.

**Comment by kfpotts1** [comment]
@storytellerr This is currently a college course project which for the length of the course will be closed to just course members. If the project is worth continuing once the course is complete then we would probably consider opening it up to the community!
