### ISSUE TITLE
"Daddy" Controller Parent

### ISSUE THREAD

**Issue by ericjunker** [kfpotts1/mp.Me#23]
This class acts as a parent for each screen's JavaFX controller.

Done:
Each screen has default abilities and buttons that allows the user to switch screens

**Comment by wisejackfr0st** [comment]
i dont know how to add time worked on but its at: 1.5 hrs

**Comment by wisejackfr0st** [comment]
I've been forgetting to update this but I've spent *2.5* hrs on this alone and *4* hrs with Ben

**Comment by wisejackfr0st** [comment]
**4.5** hrs alone and **4** hours with Ben

**Comment by wisejackfr0st** [comment]
**1.5** hrs last night
