### ISSUE TITLE
"Mommy" UI Template Parent

### ISSUE THREAD

**Issue by ericjunker** [kfpotts1/mp.Me#24]
This class acts as the parent class for the contents of each screen.

Done: 
Each screen can display text, images, and buttons from the parent class.

**Comment by wisejackfr0st** [comment]
i dont know how to add time worked on but its at: 1.5 hrs

**Comment by wisejackfr0st** [comment]
spent another hour with mommy today. up to **2.5** hrs

**Comment by wisejackfr0st** [comment]
**1** hr added up to **3.5**
