### ISSUE TITLE
Options Menu - Date Tolerance for deletion

### ISSUE THREAD

**Issue by wisejackfr0st** [kfpotts1/mp.Me#39]
done:
User can set a date to be the "tolerance checker" for the deletion recommendation screen. IE: Set to April 12th, 2016 and all files that haven't been opened before then will be recommended.

**Comment by benleblanket** [comment]
2hrs: setting month, day, year range checks. Note: month and day must be written with 2 digits even with 1 digit numbers. ie. 01/06/1997. Not 1/6/1997

**Comment by benleblanket** [comment]
2hr: further improving checks for valid input in date's text field.
