### ISSUE TITLE
Delete Menu - Recommend old files for deletion in specified directory

### ISSUE THREAD

**Issue by wisejackfr0st** [kfpotts1/mp.Me#41]
done:
Files are recommended to be deleted if they are outside of the date tolerance set in options. Files should be moved to a new folder within their set directory that contains all files recommended for deletion.

**Comment by wisejackfr0st** [comment]
Move reccommended files to a folder called toDelete; user can delete this folder to get rid of files en masse or let it rot 
(we basically want to have a tentative and hands-off approach with file deletion)

**Comment by kfpotts1** [comment]
worked for about 2.25 hours here
 - having issues reading in output for parsing.

**Comment by kfpotts1** [comment]
1.75 hours, same old story. Also I talked to Doug about this, and he gave no major insights

**Comment by kfpotts1** [comment]
2 hours, changing method from shell commands to File class

**Comment by kfpotts1** [comment]
1.5 Worked on parsing date format and comparing dates

**Comment by kfpotts1** [comment]
1.5 working with SimpleDateFormat

**Comment by kfpotts1** [comment]
0.75, added ability to search recursively in subdirectories for files

**Comment by kfpotts1** [comment]
4 hours, I think this one is just about polished off

**Comment by kfpotts1** [comment]
1 hour, submitted pull request for branch, is not linked to GUI yet, but functioning
